#!/bin/bash
#
# chkconfig: 35 90 12
# description: cmpp2filter server
#
 
# Get function from functions library
. /etc/init.d/functions
 
# Start the service cmpp2filter
start() {
        echo -n $"Starting cmpp2filter server: "
        /opt/sms-impl/cmpp2filter > /dev/null &
        # daemon /opt/sms-impl/cmpp2filter &
        ### Create the lock file ###
        touch /var/lock/subsys/cmpp2filter
        success $"cmpp2filter server startup"
        echo
}
 
# Restart the service cmpp2filter
stop() {
        echo -n $"Stopping cmpp2filter server: "
        killproc cmpp2filter
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/cmpp2filter
        echo
}
rc=
### main logic ###
case "$1" in
  start)
        stop
        sleep 1
        start
rc=${?}
        ;;
  stop)
        stop
rc=${?}
        ;;
  status)
        status cmpp2filter
rc=${?}
        ;;
  restart)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
 
exit ${rc}