#!/bin/bash
#
# chkconfig: 35 90 12
# description: cmpp2file server
#
 
# Get function from functions library
. /etc/init.d/functions
 
# Start the service cmpp2file
start() {
        echo -n $"Starting cmpp2file server: "
        /opt/sms-impl/cmpp2file > /dev/null &
        # daemon /opt/sms-impl/cmpp2file &
        ### Create the lock file ###
        touch /var/lock/subsys/cmpp2file
        success $"cmpp2file server startup"
        echo
}
 
# Restart the service cmpp2file
stop() {
        echo -n $"Stopping cmpp2file server: "
        killproc cmpp2file
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/cmpp2file
        echo
}
rc=
### main logic ###
case "$1" in
  start)
        stop
        sleep 1
        start
rc=${?}
        ;;
  stop)
        stop
rc=${?}
        ;;
  status)
        status cmpp2file
rc=${?}
        ;;
  restart)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
 
exit ${rc}