#!/bin/bash
#
# chkconfig: 35 90 12
# description: cmpp2celery server
#
 
# Get function from functions library
. /etc/init.d/functions
 
# Start the service cmpp2celery
start() {
        echo -n $"Starting cmpp2celery server: "
        cd /opt/sms-impl/
        su apache -c 'celery multi start "worker-X" -A X --autoscale=4,2 --pidfile="/var/run/celery/%N.pid" --logfile="/var/log/celery/%N.log"' > /dev/null &
        # daemon /opt/sms-impl/cmpp2celery &
        ### Create the lock file ###
        touch /var/lock/subsys/cmpp2celery
        success $"cmpp2celery server startup"
        echo
}
 
# Restart the service cmpp2celery
stop() {
        echo -n $"Stopping cmpp2celery server: "
        celery multi stopwait "worker-X" --pidfile="/var/run/celery/%N.pid"
        killproc cmpp2celery
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/cmpp2celery
        echo
}
rc=
### main logic ###
case "$1" in
  start)
        stop
        sleep 1
        start
rc=${?}
        ;;
  stop)
        stop
rc=${?}
        ;;
  status)
        status cmpp2celery
rc=${?}
        ;;
  restart)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
 
exit ${rc}