#!/bin/bash
#
# chkconfig: 35 90 12
# description: cmpp2d server
#
 
# Get function from functions library
. /etc/init.d/functions
 
# Start the service cmpp2d
start() {
        echo -n $"Starting cmpp2d server: "
        /opt/sms-impl/cmpp2d > /dev/null &
        # daemon /opt/sms-impl/cmpp2d &
        ### Create the lock file ###
        touch /var/lock/subsys/cmpp2d
        success $"cmpp2d server startup"
        echo
}
 
# Restart the service cmpp2d
stop() {
        echo -n $"Stopping cmpp2d server: "
        killproc cmpp2d
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/cmpp2d
        echo
}
rc=
### main logic ###
case "$1" in
  start)
        stop
        sleep 1
        start
rc=${?}
        ;;
  stop)
        stop
rc=${?}
        ;;
  status)
        status cmpp2d
rc=${?}
        ;;
  restart)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
 
exit ${rc}