#!/bin/bash
#
# chkconfig: 35 90 12
# description: forward server
#
 
# Get function from functions library
. /etc/init.d/functions
 
# Start the service forward
start() {
        echo -n $"Starting forward server: "
        /opt/sms-impl/forward > /dev/null &
        # daemon /opt/sms-impl/forward &
        ### Create the lock file ###
        touch /var/lock/subsys/forward
        success $"forward server startup"
        echo
}
 
# Restart the service forward
stop() {
        echo -n $"Stopping forward server: "
        killproc forward
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/forward
        echo
}
rc=
### main logic ###
case "$1" in
  start)
        stop
        sleep 1
        start
rc=${?}
        ;;
  stop)
        stop
rc=${?}
        ;;
  status)
        status forward
rc=${?}
        ;;
  restart)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
 
exit ${rc}